apiVersion: apps/v1
kind: Deployment
metadata:
  name: scone-cli
  namespace: scone
  labels:
    app: scone-cli
spec:
  selector:
    matchLabels:
      app: scone-cli
  template:
    metadata:
      namespace: scone
      labels:
        app: scone-cli
    spec:
      imagePullSecrets:
        - name: sconeapps
      containers:
        - name: scone-cli
          image: registry.scontain.com/scone.cloud/sconecli:5.8.0
          imagePullPolicy: IfNotPresent
          command: ["sleep"]
          args: ["1000000000"]
