---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scone-cli
  namespace: scone
  labels:
    app: scone-cli
spec:
  selector:
    matchLabels:
      app: scone-cli
  template:
    metadata:
      namespace: scone
      labels:
        app: scone-cli
    spec:
      imagePullSecrets:
        - name: sconeapps
      containers:
        - name: scone-cli
          image: registry.scontain.com/scone.cloud/sconecli:5.8.0
          imagePullPolicy: IfNotPresent
          command: ["sleep"]
          args: ["1000000000"]

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: scone
  name: las
  labels:
    app.kubernetes.io/name: las
    app.kubernetes.io/instance: las
    app: las
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: las
      app.kubernetes.io/instance: las
      app: las
  template:
    metadata:
      namespace: scone
      labels:
        app.kubernetes.io/name: las
        app.kubernetes.io/instance: las
        app: las
    spec:
      imagePullSecrets:
        - name: sconeapps
      containers:
        - name: las
          image: registry.scontain.com/scone.cloud/las:5.8.0
          imagePullPolicy: "IfNotPresent"
          securityContext:
            capabilities:
              add: ["SYS_RAWIO"]
          ports:
          - containerPort: 18766
            name: attestation
            protocol: TCP
            hostPort: 18766
          resources:
            limits:
              sgx.intel.com/enclave: 1

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: las-sgxdevplugin
  namespace: kube-system
  labels:
    app.kubernetes.io/name: sgxdevplugin
    app.kubernetes.io/instance: las
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sgxdevplugin
      app.kubernetes.io/instance: las
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sgxdevplugin
        app.kubernetes.io/instance: las
    spec:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      hostNetwork: true
      imagePullSecrets:
      - name: sconeapps
      containers:
      - name: sgxdevplugin
        image: registry.scontain.com/scone.cloud/sgx-plugin:5.8.0
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: dev
          mountPath: /dev
        env:
        - name: MAX_SGX_PODS
          value: "20"
        - name: LABEL_NODES
          value: "false"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: dev
        hostPath:
          path: /dev
