apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: las-sgxdevplugin
  namespace: kube-system
  labels:
    app.kubernetes.io/name: sgxdevplugin
    app.kubernetes.io/instance: las
    app.kubernetes.io/version: "1.0.0"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sgxdevplugin
      app.kubernetes.io/instance: las
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sgxdevplugin
        app.kubernetes.io/instance: las
    spec:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      hostNetwork: true
      containers:
      - name: sgxdevplugin
        image: "registry.scontain.com:5050/sconecuratedimages/kubernetes:k8s-sgx-plugin"
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: dev
          mountPath: /dev
        env:
        - name: MAX_SGX_PODS
          value: "20"
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: dev
        hostPath:
          path: /dev
