apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cas
  name: cas
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  - name: "18765"
    port: 18765
    targetPort: 18765
  selector:
    io.kompose.service: cas
status:
  loadBalancer: {}

----

apiVersion: v1
kind: ConfigMap
metadata:
  name: cas-config
data:
  cas-default-owner-config.toml: |
    [ias]
    spid            = "00000000000000000000000000000000"
    linkable_quotes = true
    sp_key          = "00000000000000000000000000000000"

  cas.toml: |
    [database]
    path = "/etc/cas/cas.db"

    [api]
    api_listen = "0.0.0.0:8081"
    enclave_listen = "0.0.0.0:18765"
