apiVersion: v1
kind: Pod
metadata:
  namespace: cas
  creationTimestamp: null
  labels:
    io.kompose.service: cas
  name: cas
spec:
  initContainers:
  - name: init-cas
    image: registry.scontain.com/scone.cloud/cas
    command:
    - sh
    - -c
    - "set -m ; cd /etc/cas; export SCONE_LAS_ADDR=127.0.0.1:18766 ; cas provision --owner-config /etc/cas/cas-default-owner-config.toml"
    volumeMounts:
    - mountPath: /etc/cas/
      name: cas-claim0
    securityContext:
      privileged: true
  containers:
  - args:
    - cas
    - -c
    - /etc/cas/cas.toml
    env:
    - name: SCONE_LAS_ADDR
      value: 172.17.0.1
    - name: SCONE_LOG
      value: info
    - name: SCONE_MODE
      value: HW
    image: registry.scontain.com/scone.cloud/cas
    name: cas
    ports:
    - containerPort: 8081
    - containerPort: 18765
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/cas/
      name: cas-claim0
    workingDir: /etc/cas
  restartPolicy: OnFailure
  volumes:
  - name: cas-claim0
    persistentVolumeClaim:
      claimName: cas-claim0
  - name: cas-config
  configMap:
    name: cas-config
status: {}
