apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cas
  creationTimestamp: null
  labels:
    io.kompose.service: cas-claim0
  name: cas-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
